// © 2019 by Benjamin Skeen
// Licensed to be used under the MIT license.
// See the LICENSE file in the project root for more information.

using static Dapper.SqlMapper;

namespace Dapper.Wrappers
{
    /// <summary>
    /// Used to receive results from a GridReader generated by a QueryMultiple call.
    /// </summary>
    public interface IQueryResultsHandler
    {
        /// <summary>
        /// Retrieves as many results from the GridReader as needed by this handler.
        /// </summary>
        /// <param name="resultsReader">The GridReader containing the results.</param>
        void ReadResults(GridReader resultsReader);
    }
}
